color= input('Enter a color: ')
plural_nouns= input("Enter a plural noun: ")
celebrity= input("Enter a celebrity: ")
print('Roses are' + color)
print(plural_nouns + "are blue ")
print(celebrity + "loves you")